[project]
name = "http-crud-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sokolov-na", email = "225724418+sokolov-na@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
http-crud-api = "http_crud_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
